[package]
name = "alarm"
version = "0.1.0"
authors = ["Aron Granberg <aron.granberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rodio = { git = "https://github.com/RustAudio/rodio", rev = "3bc614f" }
rodio = "0.11.0"
synthrs = { git = "https://github.com/gyng/synthrs", rev = "265ca00" }
rustfft = "3.0"
rocket = "0.4.5"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
rand = "0.7"
thiserror = "1.0"

# [patch.crates-io]
# cpal = { git = "https://github.com/RustAudio/cpal.git", rev = "2b31fe4" }

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["json"]

[profile.release]
panic = "abort"