[package]
name = "alarm"
version = "0.1.0"
authors = ["Aron Granberg <aron.granberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rodio = { git = "https://github.com/RustAudio/rodio", rev = "3bc614f" }
synthrs = { git = "https://github.com/gyng/synthrs", rev = "265ca00" }
# rustfft = "3.0"
rocket = "0.4.10"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
rand = "0.8"
thiserror = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"

rodio = { version = "0.11.0", optional = true }

[features]
audio = ["rodio"]

# [patch.crates-io]
# cpal = { git = "https://github.com/RustAudio/cpal.git", rev = "2b31fe4" }

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["json"]

[profile.release]
panic = "abort"